name: Deploy to Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd <YOUR_PROJECT_PATH>
          git pull origin main
          pnpm install --frozen-lockfile
          pnpm run build
          sudo systemctl reload nginx
